[workspace]
authors = ["Joshua Siraj <joshua.siraj@ryerson.ca>"]
channels = ["conda-forge"]
name = "med-image_index"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
python = ">=3.11,<3.14"
jupyterlab = ">=4.5.5,<5"
numpy = "<2"

[pypi-dependencies]
med-image-index = { path = ".", editable = true }
nbia-toolkit = { git = "https://github.com/bhklab/nbia-toolkit.git", branch = "project/med-imagenet-indexing" }
openpyxl = ">=3.1.5, <4"
pyarrow = ">=15, <22"

